[package]
name = "optodice"
version = "0.1.0"
authors = ["soulflyman <soulflyman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "*"
lazy_static = "*"
iced = "0.2"
serde_json = "1.0"
serde = "1.0"
serde_derive = { version = "1.0", feature = "serde_derive" }