[package]
name = "optodice"
version = "0.1.0"
authors = ["soulflyman <soulflyman@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
json = "*"
serde_json = "1.0"
serde = "1.0"
serde_derive = { version = "1.0", feature = "serde_derive" }
gio = "*"
glib = "*"
discord-webhook = { version = "0.1.1-alpha", git = "https://github.com/soulflyman/discord-webhook", branch = "main" }
toml = "*"
#ftp = { version = "<version>", features = ["secure"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }

[dependencies.gtk]
version = "0.9.2"
feature = ["v3_24"]