name: 🍎 MacOS
on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  macos-gui:
    strategy:
      matrix:
        toolchain: [ stable ]
        type: [ release ]
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Override link[WORKAROUND] # Looks that this is a bug with current homebrew or Github CI
        run: rm '/usr/local/bin/2to3'

      - name: Install GTK3
        run: brew install rust gtk+3

      - name: Build
        run: cargo build --release --bin optodice
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
        if: ${{ matrix.type == 'release'}}

      - name: Store MacOS Build
        uses: actions/upload-artifact@v2
        with:
          name: optodice-${{ runner.os }}-${{ matrix.toolchain }}
          path: target/release/optodice
        if: ${{ matrix.type == 'release' }}
